# Generated by Django 4.0.5 on 2023-03-01 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0002_topic_room_host_message_room_topic'),
        ('chatbox', '0003_room_participants'),
    ]

    operations = [
    ]
