# Generated by Django 4.0.5 on 2023-03-01 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0004_merge_20230301_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
