# Generated by Django 3.2.11 on 2022-01-21 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratinghome', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rateinfo',
        ),
    ]
