# Generated by Django 3.2.11 on 2022-01-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratinghome', '0003_rateinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rateinfo',
            old_name='tags',
            new_name='tag',
        ),
    ]
