# Generated by Django 3.2.5 on 2022-02-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratinghome', '0005_rename_tag_rateinfo_tag_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateinfo',
            name='adventure',
            field=models.IntegerField(choices=[(0, 0), (1, 1)]),
        ),
        migrations.AlterField(
            model_name='rateinfo',
            name='culture',
            field=models.IntegerField(choices=[(0, 0), (1, 1)]),
        ),
        migrations.AlterField(
            model_name='rateinfo',
            name='history',
            field=models.IntegerField(choices=[(0, 0), (1, 1)]),
        ),
        migrations.AlterField(
            model_name='rateinfo',
            name='sightseeing',
            field=models.IntegerField(choices=[(0, 0), (1, 1)]),
        ),
        migrations.AlterField(
            model_name='rateinfo',
            name='wildlife',
            field=models.IntegerField(choices=[(0, 0), (1, 1)]),
        ),
    ]
