# Generated by Django 3.2.5 on 2022-02-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratinghome', '0006_auto_20220215_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rateinfo',
            old_name='tag_title',
            new_name='tags',
        ),
        migrations.AddField(
            model_name='rateinfo',
            name='child_friendly',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='rateinfo',
            name='religious',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='rateinfo',
            name='adventure',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='rateinfo',
            name='culture',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='rateinfo',
            name='history',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='rateinfo',
            name='sightseeing',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='rateinfo',
            name='wildlife',
            field=models.BooleanField(default=0),
        ),
    ]
