# Generated by Django 3.2.11 on 2022-01-26 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destination', '0002_auto_20220126_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='blogimages')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('related_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destination.places')),
            ],
        ),
        migrations.CreateModel(
            name='blogimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogimages')),
                ('bg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
            ],
        ),
    ]
