# Generated by Django 3.2.10 on 2022-02-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_blog_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_images',
        ),
        migrations.AlterField(
            model_name='blogimages',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='blogimages'),
        ),
    ]
