# Generated by Django 3.2.5 on 2022-02-15 16:00

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20220213_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(upload_to=blog.models.th_file_name),
        ),
        migrations.AlterField(
            model_name='blogimages',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.img_file_name),
        ),
    ]
