# Generated by Django 3.2.11 on 2022-01-20 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profileform',
        ),
    ]
