# Generated by Django 3.2.11 on 2022-01-22 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_delete_profileform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Extendeduser',
        ),
    ]
