# Generated by Django 3.2.11 on 2022-01-22 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0003_delete_extendeduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culture', models.BooleanField()),
                ('wildlife', models.BooleanField()),
                ('adventure', models.BooleanField()),
                ('sightseeing', models.BooleanField()),
                ('history', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Extendeduser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=20)),
                ('sex', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('preference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.preferences')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
