# Generated by Django 3.2.11 on 2022-01-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_extendeduser_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='middle_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
