# Generated by Django 3.2.11 on 2022-01-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_extendeduser_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='adventure',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='culture',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='history',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='sightseeing',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='wildlife',
            field=models.BooleanField(null=True),
        ),
    ]
