# Generated by Django 3.2.11 on 2022-01-22 17:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0007_auto_20220122_1743'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Extendeduser',
            new_name='Profile',
        ),
    ]
