# Generated by Django 3.2.11 on 2022-01-24 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culture', models.BooleanField(default=False)),
                ('wildlife', models.BooleanField(default=False)),
                ('adventure', models.BooleanField(default=False)),
                ('sightseeing', models.BooleanField(default=False)),
                ('history', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='preference',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.preferences'),
        ),
    ]
