# Generated by Django 4.0 on 2022-01-29 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20220126_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='preference',
        ),
    ]
