# Generated by Django 3.2.5 on 2022-02-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_preferences_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='defaultpp.jpg', null=True, upload_to='profileimages'),
        ),
    ]
