# Generated by Django 3.2.5 on 2022-02-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='register_status',
            field=models.BooleanField(default=False),
        ),
    ]
