# Generated by Django 3.2.5 on 2022-02-03 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_profile_register_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='register_status',
        ),
    ]
