# Generated by Django 3.2.5 on 2022-02-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='child_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preferences',
            name='religious',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='adventure',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='culture',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='history',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='sightseeing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='wildlife',
            field=models.BooleanField(default=False),
        ),
    ]
