# Generated by Django 3.2.5 on 2022-03-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_auto_20220216_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='nationality',
            field=models.CharField(default='Nepali', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
