# Generated by Django 3.2.7 on 2023-02-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_remove_profile_is_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_guide',
            field=models.BooleanField(default=False),
        ),
    ]
