# Generated by Django 4.0 on 2022-01-29 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0004_alter_place_rating_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='ratings',
        ),
    ]
