# Generated by Django 3.2.5 on 2022-02-04 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0006_auto_20220204_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destination.places'),
        ),
    ]
