# Generated by Django 3.2.5 on 2022-02-04 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0007_alter_comment_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_date']},
        ),
    ]
