# Generated by Django 3.2.5 on 2022-02-15 13:19

import destination.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratinghome', '0006_auto_20220215_1904'),
        ('destination', '0009_alter_place_rating_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='rateinfo',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='ratinghome.rateinfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='places',
            name='thumbnail_image',
            field=models.ImageField(default='thumbnail_default.jpg', upload_to=destination.models.content_file_name),
        ),
    ]
