# Generated by Django 3.2.5 on 2022-02-15 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratinghome', '0006_auto_20220215_1904'),
        ('destination', '0011_remove_places_rateinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='rateinfo',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ratinghome.rateinfo'),
            preserve_default=False,
        ),
    ]
