# Generated by Django 3.2.5 on 2022-02-17 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0014_alter_places_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='places',
            old_name='rateinfo',
            new_name='Rateinfo',
        ),
    ]
