# Generated by Django 3.2.5 on 2022-02-17 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0015_rename_rateinfo_places_rateinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='places',
            old_name='Rateinfo',
            new_name='rateinfo',
        ),
    ]
