# Generated by Django 4.0.3 on 2022-03-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0017_mf_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='descrption',
            field=models.TextField(default=''),
        ),
    ]
